### ISSUE TITLE
使用过的无限存储单元里面有奇怪的

### ISSUE THREAD

**Issue by salieelinar** [asdflj/AE2Things#1]
![image](https://github.com/asdflj/AE2Things/assets/16777207/08043ebe-ad46-4e53-9045-a87ff9cdfe26)
![image](https://github.com/asdflj/AE2Things/assets/16777207/d8cf8750-fb58-4712-9e28-0e3ec62ec605)
![image](https://github.com/asdflj/AE2Things/assets/16777207/1d2137f9-7ce5-4811-8932-ce1ae475932d)
一个使用过的无限存储单元，在搬家后腾空了里面的物品，单独放进一个只有驱动器的网络中，会显示很多合成配方

**Comment by asdflj** [comment]
修好了
