### ISSUE TITLE
1.41安装后AE终端不能更新网络内物品

### ISSUE THREAD

**Issue by FSO3H** [asdflj/AE2Things#10]
取出或者放入物品都不能显示实时的物品数量

https://github.com/user-attachments/assets/b3da9c72-7af6-445a-91bf-c4c1a7b46fdd

在1.23版本未出现此问题，更新至1.41后立即出现，没有制作新版本的任何物品
使用了物品和流体的两种无限元件
在无线终端和me终端都存在此问题

**Comment by asdflj** [comment]
是否使用了原件连接功能，且在配置文件里面关闭了这个功能

**Comment by asdflj** [comment]
我无法复现这个问题，我测试的存档也没这个问题，能否提供你的存档给我看看

**Comment by asdflj** [comment]
不要用fc的终端，用原版终端也会吗

**Comment by asdflj** [comment]
fc的终端是非同步的,我用原版的元件也会出现 取出或者放入物品都不能显示实时的物品数量
![41](https://github.com/user-attachments/assets/55ecc7eb-06a4-4275-9c01-31a7a8fe01ae)

**Comment by FSO3H** [comment]
存档文件很大，由于有私货我可能还要提供完整服务端和客户端？我应该使用什么途径上传这么大的文件？
使用原版终端存在相同问题。事实上此问题最早就是原版终端发现的。

**Comment by asdflj** [comment]
加qq吧 854865755
