### ISSUE TITLE
注魔接口与炼金接口UI内仍显示ME二合一接口

### ISSUE THREAD

**Issue by Nxer** [asdflj/AE2Things#16]
![image](https://github.com/user-attachments/assets/3ca2d60c-323f-4130-ae06-0bcd569bf233)
![image](https://github.com/user-attachments/assets/54f623ad-55f1-4212-9ee9-ca6ac4312874)

**Comment by asdflj** [comment]
不是bug,只是实现起来很麻烦,懒得搞

**Comment by asdflj** [comment]
用asm搞完了
