### ISSUE TITLE
能否添加打开背包终端的快捷键

### ISSUE THREAD

**Issue by liansishen** [asdflj/AE2Things#2]
类似无线终端一样的，不需要拿在手里就可以打开终端

**Comment by asdflj** [comment]
搞定了

**Comment by asdflj** [comment]
![image](https://github.com/asdflj/AE2Things/assets/33802162/ad8607c7-d877-40ed-8eb0-c03b22e76ccc)

**Comment by liansishen** [comment]
> ![image](https://private-user-images.githubusercontent.com/33802162/336699853-ad8607c7-d877-40ed-8eb0-c03b22e76ccc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NjYxOTUsIm5iZiI6MTcxNzU2NTg5NSwicGF0aCI6Ii8zMzgwMjE2Mi8zMzY2OTk4NTMtYWQ4NjA3YzctZDg3Ny00MGVkLThlYjAtYzAzYjIyZTc2Y2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA1MzgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMzYwYzUzOTU2NGU0NjYwMDFhODI1ZTk1MGViNGIyOWFlOTFlNDljZGUxMjg5YzU3NzRiMzhlYThhNTVhNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z-kLDooEFKcOoBKMfSVqm-6Qv3ghp03lsl9LggwbQ2M)

大佬好迅速

**Comment by asdflj** [comment]
还有一个bug需要修复

**Comment by asdflj** [comment]
可以了

**Comment by asdflj** [comment]
![9be21cdbc1e0b1831a7838d8e61879e3](https://github.com/asdflj/AE2Things/assets/33802162/763e75b2-3d94-48ae-886b-89c64f5e99fe)
元件链接功能

**Comment by liansishen** [comment]
> ![9be21cdbc1e0b1831a7838d8e61879e3](https://private-user-images.githubusercontent.com/33802162/336706668-763e75b2-3d94-48ae-886b-89c64f5e99fe.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NjgwNTEsIm5iZiI6MTcxNzU2Nzc1MSwicGF0aCI6Ii8zMzgwMjE2Mi8zMzY3MDY2NjgtNzYzZTc1YjItM2Q5NC00OGFlLTg4NmItODljNjRmNWU5OWZlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA2MDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzYTFkMmNiMzYzODA3ZGQxNTlkMTQ3NmE1YzRkMjVjYjBiZjBhMDIwYWYwYzI1NzU4ZGIxZTdiNjViMjBiNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7QiexwGNG5uSj9ZVo0oMj6JkdUcgsQgyx6efUgJjXho) [ ](https://private-user-images.githubusercontent.com/33802162/336706668-763e75b2-3d94-48ae-886b-89c64f5e99fe.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NjgwNTEsIm5iZiI6MTcxNzU2Nzc1MSwicGF0aCI6Ii8zMzgwMjE2Mi8zMzY3MDY2NjgtNzYzZTc1YjItM2Q5NC00OGFlLTg4NmItODljNjRmNWU5OWZlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA2MDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzYTFkMmNiMzYzODA3ZGQxNTlkMTQ3NmE1YzRkMjVjYjBiZjBhMDIwYWYwYzI1NzU4ZGIxZTdiNjViMjBiNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7QiexwGNG5uSj9ZVo0oMj6JkdUcgsQgyx6efUgJjXho) ![9be21cdbc1e0b1831a7838d8e61879e3](https://private-user-images.githubusercontent.com/33802162/336706668-763e75b2-3d94-48ae-886b-89c64f5e99fe.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NjgwNTEsIm5iZiI6MTcxNzU2Nzc1MSwicGF0aCI6Ii8zMzgwMjE2Mi8zMzY3MDY2NjgtNzYzZTc1YjItM2Q5NC00OGFlLTg4NmItODljNjRmNWU5OWZlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA2MDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzYTFkMmNiMzYzODA3ZGQxNTlkMTQ3NmE1YzRkMjVjYjBiZjBhMDIwYWYwYzI1NzU4ZGIxZTdiNjViMjBiNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7QiexwGNG5uSj9ZVo0oMj6JkdUcgsQgyx6efUgJjXho) [ ](https://private-user-images.githubusercontent.com/33802162/336706668-763e75b2-3d94-48ae-886b-89c64f5e99fe.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NjgwNTEsIm5iZiI6MTcxNzU2Nzc1MSwicGF0aCI6Ii8zMzgwMjE2Mi8zMzY3MDY2NjgtNzYzZTc1YjItM2Q5NC00OGFlLTg4NmItODljNjRmNWU5OWZlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA2MDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzYTFkMmNiMzYzODA3ZGQxNTlkMTQ3NmE1YzRkMjVjYjBiZjBhMDIwYWYwYzI1NzU4ZGIxZTdiNjViMjBiNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7QiexwGNG5uSj9ZVo0oMj6JkdUcgsQgyx6efUgJjXho) 元件链接功能

这个功能真不错，有几个问题
是否可以跨纬度
是否对所有元件有效

**Comment by asdflj** [comment]
可以在配置文件里面禁用
