### ISSUE TITLE
这注魔接口有什么用？

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [asdflj/AE2Things#22]
本来以为能和源质一起投进去子网络，但实际一样要普通ME接口才行，流体封包卡在接口进不去

**Comment by asdflj** [comment]
注魔用

**Comment by asdflj** [comment]
https://github.com/user-attachments/assets/8962969c-cb83-41a8-b52a-1e1780024f30

**Comment by NNNNMMMMIIII** [comment]
懂了
