### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by liansishen** [asdflj/AE2Things#3]
1.旅行者腰带切换工具栏后，背包终端无法读取被切换掉的工具栏中放着的背包里的物品
2.探险者背包背在身上后，背包终端无法读取其中物品
3.背包终端打开的情况下，鼠标在NEI中的物品上悬停一会之后，背包终端的搜索框会自动填入悬停物品的名字

**Comment by asdflj** [comment]
1.旅行者腰带,这啥?没用过
2.这个兼容问题,我看看能不能搞
3.这是特地写的,我觉得很有意思

**Comment by asdflj** [comment]
我看了下旅行者腰带的代码,兼容起来巨麻烦

**Comment by liansishen** [comment]
> 我看了下旅行者腰带的代码,兼容起来巨麻烦

那就算了，不把背包放在工具栏就行了

**Comment by asdflj** [comment]
2.现在添加了支持了,背包终端可以兼容背在身上的背包了
3.可以了,现在背包终端默认不自动填充物品名字了,可以在配置文件里面另行开启

**Comment by liansishen** [comment]
> 2.现在添加了支持了,背包终端可以兼容背在身上的背包了 3.可以了,现在背包终端默认不自动填充物品名字了,可以在配置文件里面另行开启

太有效率了

**Comment by asdflj** [comment]
@liansishen 现在终端添加了磁铁功能,shift 右击就可以切换了, 你试试看
