### ISSUE TITLE
与热力膨胀MOD冲突

### ISSUE THREAD

**Issue by ailanlana** [asdflj/AE2Things#34]
错误报告
https://pastes.dev/j6UjsDnE9H

**Comment by asdflj** [comment]
gtnh有加热力膨胀吗

**Comment by ailanlana** [comment]
没有，是我个人整合包添加的。

**Comment by asdflj** [comment]
错误报告里面看不出来,需要你提供一下mod让我看看

**Comment by asdflj** [comment]
你确定是ae2thing的问题吗,我只加热力的mod也进不去游戏

**Comment by ailanlana** [comment]
> 你确定是ae2thing的问题吗,我只加热力的mod也进不去游戏

我这边热力是可以正常运行的，添加ae2thing运行时才会出现此崩溃

**Comment by asdflj** [comment]
![image](https://github.com/user-attachments/assets/f55a4d0e-f416-452f-8d61-80f0f189f541)

**Comment by asdflj** [comment]
提供一下整合包文件,我看看

**Comment by ailanlana** [comment]
方便QQ联系吗，我QQ发你

**Comment by asdflj** [comment]
你的号码发一下,我加你好友

**Comment by ailanlana** [comment]
已在最新版本中修复
