### ISSUE TITLE
2.7.0使用注魔终端下单时崩溃

### ISSUE THREAD

**Issue by PinkYuDeer** [asdflj/AE2Things#37]
在2.7.0beta4中，发生了以下状况：
1、蒸馏配方（分解物品到源质）如果没有扫描过，右边会铺满问号，并且扫描后再次写入无法正常识别，退出重进服务器后才能写入。
2、自动识别蒸馏配方的要素实际上与ae中的不是一个东西，ae不认，放在接口中样板呈现黑紫色并且无法从终端中搜到。
![image](https://github.com/user-attachments/assets/27ff3f0c-c1cd-4a04-923e-ebf66fd3b48b)

3、手动更改为ae承认的要素配方运行正常时、哪怕网络中有源质分离器、也无法被转换为注魔样板写入时的玻璃安瓿的形式。

**Comment by asdflj** [comment]
1.是因为用了缓存技术,你需要清除物品然后再放入物品才能正常识别
2.AE2Thing的要素和TCNEIAdditions提供的蒸馏要素不是同一个类型的东西,AE2Thing提供是的流体,而TCNEIAdditions提供的是物品,普通的终端无法是单独类型的,只能监控物品或者流体,只有注魔终端和二合一接口终端是物品和流体都监控的终端
3..AE2Thing的要素和其他mod提供的不是同一种东西,不要手动更改,
AE2Thing的要素和其他mod提供的不是同一种东西,不要手动更改,
AE2Thing的要素和其他mod提供的不是同一种东西,不要手动更改
重要的事情说三遍

**Comment by PinkYuDeer** [comment]
![image](https://github.com/user-attachments/assets/485b81dc-df17-41b0-bad0-de9ae5c7fd8f)
![image](https://github.com/user-attachments/assets/74945a71-8de2-471b-8d34-bf8494db5441)
![image](https://github.com/user-attachments/assets/f42a2e9a-c45e-41e4-a943-b6aea01d72ed)
![image](https://github.com/user-attachments/assets/048f5170-98f3-47d0-9b21-f15055d1514a)
![image](https://github.com/user-attachments/assets/32bf36df-6419-423d-b8d1-de96ccf19f67)
过程：1、打开注魔接口
2、放入已扫描物品
3、拿到样板、放入注魔接口
4、ae终端中搜索要素安瓿
5、切换成可合成无内容。

**Comment by asdflj** [comment]
用注魔终端或者二合一终端

**Comment by PinkYuDeer** [comment]
使用的就是注魔终端

**Comment by PinkYuDeer** [comment]
https://github.com/user-attachments/assets/72c46bfd-2e05-4a83-a969-9c6786897d70

**Comment by asdflj** [comment]
> ![image](https://private-user-images.githubusercontent.com/83949453/390399906-485b81dc-df17-41b0-bad0-de9ae5c7fd8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTA5NzQsIm5iZiI6MTczMjcxMDY3NCwicGF0aCI6Ii84Mzk0OTQ1My8zOTAzOTk5MDYtNDg1YjgxZGMtZGYxNy00MWIwLWJhZDAtZGU5YWU1YzdmZDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDEyMzExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYWIzMDE4YTExMzM0ZTg4NTFkYTI5N2U3NmVlM2Y1ODcwYWI0MDBlZGQzZmViYzg4OTI5YmI5NzIwOTAyYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XZv1W2L6sYuin_NWQ9BemrV60PMiJXvLm5hVsI9ezD4) ![image](https://private-user-images.githubusercontent.com/83949453/390399987-74945a71-8de2-471b-8d34-bf8494db5441.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTA5NzQsIm5iZiI6MTczMjcxMDY3NCwicGF0aCI6Ii84Mzk0OTQ1My8zOTAzOTk5ODctNzQ5NDVhNzEtOGRlMi00NzFiLThkMzQtYmY4NDk0ZGI1NDQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDEyMzExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYTkzMGFmMmJkZWY0ZDVlNmZkMmYwZGFjOWU1NWZkZmZiZmU5ZjM2ZDZhMGRkM2JhNGQ4ZDMxNGE1YTA4ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zBpwK8mpbwsbqn1KEJuLbH7bg7R8aViD6G7HdG0yvnY) ![image](https://private-user-images.githubusercontent.com/83949453/390400439-f42a2e9a-c45e-41e4-a943-b6aea01d72ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTA5NzQsIm5iZiI6MTczMjcxMDY3NCwicGF0aCI6Ii84Mzk0OTQ1My8zOTA0MDA0MzktZjQyYTJlOWEtYzQ1ZS00MWU0LWE5NDMtYjZhZWEwMWQ3MmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDEyMzExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZjkyMzcxYzMwODg1NjBiNzU2MDFkNzY1MzhiMDc2YzQwYjM1Yzc1NmQ5YzE2NWQ3ZDQ5ZjYzNGM5ODE1M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._6KyPypnOwZuRVG5P-_mbkyGxHTiUAdFquTsCRf0s24) ![image](https://private-user-images.githubusercontent.com/83949453/390401099-048f5170-98f3-47d0-9b21-f15055d1514a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTA5NzQsIm5iZiI6MTczMjcxMDY3NCwicGF0aCI6Ii84Mzk0OTQ1My8zOTA0MDEwOTktMDQ4ZjUxNzAtOThmMy00N2QwLTliMjEtZjE1MDU1ZDE1MTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDEyMzExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NzYxODZlZDMxMTZkZjZkMDgyN2NmNWYxNjdjYzJkZmVjYzU2MmUyZmEwYjk3OTI0OTU0YzI5Y2NhMzljMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xljcHCzQo4vN-ZuHqA4W3sjhDBiJ46Z029lRuId_x1s) ![image](https://private-user-images.githubusercontent.com/83949453/390400521-32bf36df-6419-423d-b8d1-de96ccf19f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTA5NzQsIm5iZiI6MTczMjcxMDY3NCwicGF0aCI6Ii84Mzk0OTQ1My8zOTA0MDA1MjEtMzJiZjM2ZGYtNjQxOS00MjNkLWI4ZDEtZGU5NmNjZjE5ZjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDEyMzExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNGRjODYwM2VhMmEyMGY4YjQyODY1YjAyZDAzZTA1N2QyNDE2ZWVlMGVhZjg0ZGY2ZjQ4NTFkZGJhMDM5MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iK1U56gBn5ZRo9heqN4M0zU7rwWjilHNzNK5V81H2eY) 过程：1、打开注魔接口 2、放入已扫描物品 3、拿到样板、放入注魔接口 4、ae终端中搜索要素安瓿 5、切换成可合成无内容。

我不记得我的注魔终端有这个东西
![image](https://github.com/user-attachments/assets/3e61fecb-7b6f-45e9-a5c5-14044794f39a)

**Comment by asdflj** [comment]
![image](https://github.com/user-attachments/assets/cc43a4cb-7f26-43a6-bf13-b6e4ed0a6c0b)

**Comment by PinkYuDeer** [comment]
嗷 原来下订单也需要从注魔终端。我以为只需要编写样板的时候使用注魔终端。

**Comment by PinkYuDeer** [comment]
在之前试图下单注魔合成的单子的时候也会崩溃、所以不敢用这个下单。

**Comment by asdflj** [comment]
让我see see

**Comment by asdflj** [comment]
我在开发环境下无法复现这个问题,奇怪了

**Comment by asdflj** [comment]
> 在之前试图下单注魔合成的单子的时候也会崩溃、所以不敢用这个下单。

已修复

**Comment by PinkYuDeer** [comment]
更新后不崩溃了。但是也不会计算缺失的要素安瓿（到要素）
这是预期行为吗？我是否需要结合 高级注魔供应器 来使用？
![image](https://github.com/user-attachments/assets/6d178633-bc24-49e9-bae8-7cf5bac03741)

**Comment by PinkYuDeer** [comment]
（是注魔终端下单。

**Comment by asdflj** [comment]
要素不等于要素安瓿瓶，要素是由源质离散器转为要素安瓿瓶

**Comment by PinkYuDeer** [comment]
问题是网络中有要素合成方式、有源质离散器的情况下 缺少的要素安瓿不会自动转换orz

**Comment by PinkYuDeer** [comment]
如果这是预期行为的话、我就直接写要素安瓿的蒸馏配方了qwq

**Comment by asdflj** [comment]
是预期行为
