### ISSUE TITLE
安装1.39后服务端后台出现异常报错刷屏

### ISSUE THREAD

**Issue by Nxer** [asdflj/AE2Things#9]
![$NKN%IPC)}$XPTJH`27H9WR](https://github.com/user-attachments/assets/b5346046-c03a-4ca0-803c-9a92b2fb03db)

GTNH-2.6.1

**Comment by asdflj** [comment]
你这个我啥也看不出来,有没有日志文件

**Comment by Nxer** [comment]
> 你这个我啥也看不出来,有没有日志文件

这个就是服务端的后台实时日志了。不过报错没有从ae2thing 起所以来问一下有没有遇到过类似的情况。不过删除ae2thing后恢复正常了。猜测可能和神秘能源的源质流体加载有关。

**Comment by asdflj** [comment]
我自己测试用的存档没问题

**Comment by asdflj** [comment]
你是不是放置了源质离散器?

**Comment by Nxer** [comment]
> 我自己测试用的存档没问题

拿一个神秘能源的魔导源质元件(就是创造源质原件)再标记后塞进网络内呢？

没有放源质离散器，只是安装后任何功能都没使用，然后看到后台在报这个就没有继续使用下去了。

**Comment by asdflj** [comment]
2.6.1好像没这个物品

**Comment by asdflj** [comment]
找到了

**Comment by asdflj** [comment]
![image](https://github.com/user-attachments/assets/452576fe-8ef1-45dc-8ae0-e62e6c93caa5)

**Comment by asdflj** [comment]
没有报错

**Comment by Nxer** [comment]
> 没有警告

所有63种源质都标记一下呢

**Comment by asdflj** [comment]
![image](https://github.com/user-attachments/assets/00d5af07-ba9d-41d3-b6ce-1b423a604677)

**Comment by asdflj** [comment]
这个要素添加进去就会报错

**Comment by Nxer** [comment]
> 这个要素添加进去就会报错

好好好，这就是穷举法的实力，剩下的交给老登了

**Comment by asdflj** [comment]
gt的问题

**Comment by Nxer** [comment]
乐

**Comment by asdflj** [comment]
gt和神秘能源 注册成流体的顺序有问题,漏了这个要素,所以会报npe

**Comment by asdflj** [comment]
修好了

**Comment by Nxer** [comment]
done
